### ISSUE TITLE
Access is denied: 'NetJSON.NetJSONSerializer....'     When trying to serialize a simple Struct

### ISSUE THREAD

**Issue by omerbn** [rpgmaker/NetJSON#103]
When try to serialize the following Struct, I get "TypeInitializationException" with "Access is denied: 'NetJSON.NetJSONSerializer" as the innerException.
## Stack:
>
>   at NetJSON.NetJSON.GetSerializer[T]()
>   at NetJSON.NetJSON.Serialize[T](T value)
>   at Console_CS.Program.Main(String[] args) in ..../Program.cs:line 165
>   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Threading.ThreadHelper.ThreadStart()

### More info:
>struct Simple
>{
>    public int x;
>    public long y;
>}

.Net version:   4.5.1

**Comment by rpgmaker** [comment]
That is really weird. Can you try making them properties to see if the errors still occurs? Trying to  narrow down the issue.

Thanks,

**Comment by rpgmaker** [comment]
It is indeed a simple struct. The issue is that I don't support non public types. Make it public and it does work.

Thanks,

**Comment by omerbn** [comment]
1. Thanks, it's good to know. Do you plan on supporting private/protected structs/classes?
2. I took the "public struct Vector3" example from your tests, and got the same exception. :(

**Comment by rpgmaker** [comment]
Make sure that the class is not inside another class that is private or internal. I tested it

Thanks,

**Comment by rpgmaker** [comment]
I have plan for supporting the non public classes and members. It is just a lot of rewrote and moving things around since my code is not based on dynamic methods but rather dynamic assembly. Coming up with an hybrid solution requires a lot of rethinking on my part so I don't break other parts of the code.

Currently there is an open item for the non public support. I will start to look at it as soon as I implement the other request for using settings class to customize serialization and deserialization rather than using static.

Thanks,

**Comment by omerbn** [comment]
Cool!

**Comment by wmjordan** [comment]
> It is just a lot of rewrote and moving things around since my code is not based on dynamic methods but rather dynamic assembly. Coming up with an hybrid solution requires a lot of rethinking on my part so I don't break other parts of the code.

Currently _NetJSON_ uses a static generic type to avoid explicit locking and synchronizing in multiple threading environments. Therefore, the first hard problem is that the `TypeBuilder` will not allow us to create a public `JsonSerializer<TNonPublicType>`. It appears that the generic cache part must be reconstructed.

**Comment by rpgmaker** [comment]
The generic cache is not the problem because you can still pass the defined non public class to it. The problem is that I don't pick up the non public fields/properties. At the moment I do process non  public setter if the property definition is public. To fully support non public classes. I have to add an attribute that let you ignore specific fields else it will pick everything in the class when reading all non public fields and properties of the class. I will also need be able to call the constructor of the class similar to the way it is currently be done. And for unknown type that are non public, I already have a method for serialize and deserialize that takes Type and generate dynamic method to properly pass the right type constraints to the static initializer.

Thanks

**Comment by wmjordan** [comment]
Hi,

Thank you for your reply.
Why the generic cache mechanism will break is not because the generic will not accept the generic type, but the `TypeBuilder` will refuse to create the serializer type having a non-public type as its parent type.
The following line is fine:
````C#
var type = module.DefineType(String.Concat(objType.GetName(), ClassStr), TypeAttribute, genericType);
````
But the following line will fail with a `TypeInitializationException` saying that _Access is denied_:
````C#
returnType = type.CreateType();
````
To quickly verify this, please remove the `public` of `BaseApiResponse` in line 83 of _SerializeTests.cs_ and you will see that the unit tests will fail. No matter if we call 
````C#
var data = NetJSON.Deserialize<BaseApiResponse>(jsonData);
````
or
````C#
var data = NetJSON.Deserialize (typeof(BaseApiResponse), jsonData);
````
in line 156. It will doom to fail.

We should make the support for private members explicit, that is, by default, the feature is off. Otherwise, the compiler-auto-generated backing fields of Properties will be serialized, which will break the existing code.

**Comment by rpgmaker** [comment]
I understand now. The failure happens due to type builder. It makes sense to disable the feature of non public support by default and let the user add attribute to ignore fields and properties as needed. Since type builder will not work I will have to make use of dynamic method which should be compatible for the most part since all my generated methods are static definition.

Thanks,

**Comment by rpgmaker** [comment]
If you want to make a pull request for any of the changes, you are welcome to do so.

Thanks,

**Comment by wmjordan** [comment]
I am sorry that I am still studying your code and no pull request at this moment :P
I was impressed by the astonishing performance of _NetJSON_ and then began to learn from it.
It is truly a gold mine.
