### ISSUE TITLE
Fix CurrentSettings

### ISSUE THREAD

**Issue by dsoronda** [rpgmaker/NetJSON#108]
I wanted to change Settings to use NetJSONFormat.Prettify.
Logical step was to write this :

NetJSON.NetJSONSettings.CurrentSettings.Format = NetJSONFormat.Prettify;

I assumed that later in code, when I call NetJSON.NetJSON.Serialize(someObject), my code will be prettified. Gosh, I was so wrong, and then I looked at NetJSON.NetJSONSettings.CurrentSettings implentation.
``` C#
public static NetJSONSettings CurrentSettings {
            get {
                return new NetJSONSettings(); // WUT ??
            }
}
```
That is so wrong or I can't see logic behind it ??

Please write some documentation how we can use NetJSON with global Settings.
Thanks.

**Comment by rpgmaker** [comment]
You are not suppose to use the global setting. I am planning on
depreciating it. You should be using the serialize method and passing
setting object to it and not updating the current object as you doing now.

It should be more like.

NetJson.Serialize (obj, new NetJsonSettings {})

Thanks,

I wanted to change Settings to use NetJSONFormat.Prettify.
Logical step was to write this :

NetJSON.NetJSONSettings.CurrentSettings.Format = NetJSONFormat.Prettify;

I assumed that later in code, when I call
NetJSON.NetJSON.Serialize(someObject), my code will be prettified. Gosh, I
was so wrong, and then I looked at NetJSON.NetJSONSettings.CurrentSettings
implentation.

public static NetJSONSettings CurrentSettings {
            get {
                return new NetJSONSettings(); // WUT ??
            }
}

That is so wrong or I can't see logic behind it ??

Please write some documentation how we can use NetJSON with global Settings.
Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rpgmaker/NetJSON/issues/108>, or mute the thread
<https://github.com/notifications/unsubscribe/AAiC795ohFwdRJ2EGl8VMXoVJEgR5NX1ks5qKXyYgaJpZM4IzCb8>
.

**Comment by rpgmaker** [comment]
The public static is used internally for backward compatibility of netjson setting. It has to be public to be accessed by cil.

Thanks,

**Comment by rpgmaker** [comment]
I am closing this since it is not an issue. Let me know if anything needs to done by opening a new issue.

Thanks,
