### ISSUE TITLE
IntUtility not working

### ISSUE THREAD

**Issue by imacks** [rpgmaker/NetJSON#158]
I am only getting 0-9 correct when calling IntUtility.itoa

From 10-9999 only the first digit survives. Any number beyond that turns into an empty string :(

**Comment by rpgmaker** [comment]
Hi,

Just curious, why are you calling the method directly?. There is a different method call IntToStr if you are just using integer conversion from the library only. Most things are not used from IntUtility.

Thanks,

**Comment by imacks** [comment]
I am just wondering if this is on the fix todo list.

**Comment by rpgmaker** [comment]
I will clean it up during the performance update that I have planned.

Thanks,

**Comment by rpgmaker** [comment]
Feel free to help me resolve it by creating a pull request.

**Comment by rpgmaker** [comment]
Since I recently marked most of the internally used classes as internal. I don't know if this is still valid. The intention was not to make a int utility class available. I am going to close this for now. If this is still important to you, i can fix the bug if you are just utilizing the piece of code without using NetJSON directly.

Thanks,
