### ISSUE TITLE
internal type support?

### ISSUE THREAD

**Issue by tanglebones** [rpgmaker/NetJSON#49]
Can we generate all types into the same assembly name (e.g. NetJsonEmitted) so we can mark InternalsVisiableTo from our assembly to that assembly?

Having to mark serialization types as public leaks those details into the public API of the assembly, which I'd like to avoid if possible.

**Comment by rpgmaker** [comment]
There is an open item to allow non public serialization. I have not take
time to implement it yet. But once I do implement it, it will solve this
issue with internal and private types.

Thanks,

Can we generate all types into the same assembly name (e.g. NetJsonEmitted)
so we can mark InternalsVisiableTo from our assembly to that assembly?

Having to mark serialization types as public leaks those details into the
public API of the assembly, which I'd like to avoid if possible.

—
Reply to this email directly or view it on GitHub
<https://github.com/rpgmaker/NetJSON/issues/49>.

**Comment by tanglebones** [comment]
Yep; saw that. This is just a different idea on how to get there, since using InternalsVisibleTo already should work as-is; but requires adding one entry for every data class since they all go into different assemblies.

**Comment by rpgmaker** [comment]
The issue of using one assembly for all classes is that I will have scan the entire application to detect classes that needs to be stored in this single dll. Rather than progressively generate emitted dll as the class are serialized or deserialized which will mean a longer startup time.

But may in the future I can create a process to generate a single dll that can be preprocess to contain everything. So it can later be reference without having to reference Netjson.

**Comment by rpgmaker** [comment]
Closing this issue since it is same as https://github.com/rpgmaker/NetJSON/issues/10.
