### ISSUE TITLE
Add PCL

### ISSUE THREAD

**Issue by jorisdebock** [rpgmaker/NetJSON#56]
Are there any plans for a PCL? So it can be used in windows universal projects etc.

**Comment by rpgmaker** [comment]
I have not really looked into the support for portable yet. But I can support it as long as the target platform has reflection.emit and unsafe.

**Comment by rpgmaker** [comment]
There seem that there is no support for TypeBuilder and MethodBuilder which is essential to fully support the code generating aspect of NetJSON. I will do more research see if this is going to be possible or not.

**Comment by Licshee** [comment]
TypeBuilder & MethodBuilder are only supported in .NET Framework & Silverlight, you can use only DynamicMethod for other CLI platforms.

Or you could also try Cecil, which is an alternate to the .NET Emit thing, and it added PCL support recently.

If you are not going to start it any soon, i might try to port it some time later.

**Comment by rpgmaker** [comment]
It will be nice if you are able to port the code for use in pcl since I will not be working on this soon, since I am still trying to get non private type serialization working with lost of functionality. I was hoping that the port will not completely branch away from the current base but rather try as much as possible to use similar code base. Using the same project help when there is changes that needs to be done for all the various version of .net.

I will suggest that if you planning to port that you consider breaking the methods into callable code that will work both for dynamic methods and assembly since 99% of the code is generating static methods which benefits dynamic methods style. 

Thanks for considering to help.

**Comment by Licshee** [comment]
Thanks, I'll let you know when I start working on it.

**Comment by rpgmaker** [comment]
Closing this issue since .NET Core is the focus now. .Net Core issue already created here: https://github.com/rpgmaker/NetJSON/issues/105
