### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by lbowers** [rpgmaker/NetJSON#75]
I've done a straight swap of JSON.Net with NetJSON, but my website is now failing with: "Index was outside the bounds of the array."

T obj = NetJSON.NetJSON.Deserialize< T >(json);

The json itself is quite simple:

{"Id":108591,"EmailAddress":"james.brown@dummy.com","FirstName":"James","Surname":"Brown","TitleId":597,"Address":null}

I assume the NULL is the issue?

We're serializing/deserializing models built with Mindscape's Lightspeed ORM: http://www.mindscapehq.com/products/lightspeed

**Comment by rpgmaker** [comment]
Can I see your data structures?

Is Id declared as integer or string? I have seen json where json.net try to automatically fix types for you in such scenario and mine does not try to do so.

If you think null is the issue, can you try to remove it and see if it works. If it works then it is a simple bug I can quickly fix since I count characters for determining null and also because I ignore null value when using NetJSON.SkipDefaultValue 

Thanks,

**Comment by rpgmaker** [comment]
NetJSON.SkipDefaultValue is set to true by default

**Comment by lbowers** [comment]
I'm not sure if it's simply because of the "weight" of the object's were serializing - Lightspeed's models go quite deep (hierarchically). Having said that, the example above is light. Hmmm...

I've had to revert to JSON.Net, due to time constraints. I will revisit this and post more details/my findings when I can.

FYI: I've now tried Jil, NetJSON, JSON.Net (Newtonsoft), ServiceStack and JSON.Net is the only library that has worked with all of our objects, problem free. I'd really like to move to a more performant library though.

**Comment by rpgmaker** [comment]
Is the object a recursive json?

Thanks,

**Comment by rpgmaker** [comment]
This issue was resolved in the last checkin before this one. The commit attached just simply shows that it works from while testing it from a unit test.

The issue was caused by a string skip optimization issue that i had

Thanks

**Comment by rpgmaker** [comment]
If you have time, please test again and let me know if the issue was resolved.

Thanks,
